# Generated by Django 4.1.3 on 2023-10-16 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_like_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='userFollowed',
        ),
        migrations.RemoveField(
            model_name='like',
            name='postLiked',
        ),
        migrations.AddField(
            model_name='follow',
            name='userFollowed',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='usersFollowed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='postLiked',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='postsLiked', to='network.post'),
        ),
    ]
