# Generated by Django 4.1.3 on 2023-10-16 08:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_remove_follow_userfollowed_remove_like_postliked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='postLiked',
        ),
        migrations.RemoveField(
            model_name='like',
            name='userLiking',
        ),
        migrations.AddField(
            model_name='user',
            name='postsLiked',
            field=models.ManyToManyField(blank=True, related_name='likedPosts', to='network.post'),
        ),
        migrations.AddField(
            model_name='user',
            name='usersFollowed',
            field=models.ManyToManyField(blank=True, related_name='followedUsers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
