# Generated by Django 4.1.3 on 2023-10-17 01:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_remove_like_postliked_remove_like_userliking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usersFollowed',
            field=models.ManyToManyField(related_name='followedUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
