# Generated by Django 4.1.3 on 2023-10-17 01:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_user_usersfollowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='postsLiked',
        ),
        migrations.AddField(
            model_name='post',
            name='usersLiked',
            field=models.ManyToManyField(blank=True, related_name='usersLiked', to=settings.AUTH_USER_MODEL),
        ),
    ]
