# Generated by Django 4.1.3 on 2023-10-18 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_user_postsliked_post_usersliked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userPosted', to=settings.AUTH_USER_MODEL),
        ),
    ]
